//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;

namespace FoodApp.Resources.Strings;

/// <summary>
/// Strongly-typed access to localized strings in AppResources.resx.
/// </summary>
public static class AppResources
{
    private static readonly ResourceManager ResourceManager =
        new("FoodApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);

    public static CultureInfo? Culture { get; set; }

    private static string Get(string name) =>
        ResourceManager.GetString(name, Culture) ?? name;

    public static string AppName => Get(nameof(AppName));
    public static string TabHome => Get(nameof(TabHome));
    public static string TabScan => Get(nameof(TabScan));
    public static string TabRecipes => Get(nameof(TabRecipes));
    public static string TabHistory => Get(nameof(TabHistory));
    public static string TabSettings => Get(nameof(TabSettings));
    public static string HelpTitle => Get(nameof(HelpTitle));
    public static string HelpContent => Get(nameof(HelpContent));
    public static string DarkMode => Get(nameof(DarkMode));
    public static string CalorieGoal => Get(nameof(CalorieGoal));
    public static string SaveSettings => Get(nameof(SaveSettings));
    public static string ErrorCalorieRange => Get(nameof(ErrorCalorieRange));
    public static string ErrorPortionRange => Get(nameof(ErrorPortionRange));
    public static string ErrorRequired => Get(nameof(ErrorRequired));
    public static string ErrorNetwork => Get(nameof(ErrorNetwork));
    public static string Retry => Get(nameof(Retry));
    public static string CameraUnavailable => Get(nameof(CameraUnavailable));
    public static string MicrophoneUnavailable => Get(nameof(MicrophoneUnavailable));
    public static string LocationUnavailable => Get(nameof(LocationUnavailable));
    public static string ScanFood => Get(nameof(ScanFood));
    public static string CapturePhoto => Get(nameof(CapturePhoto));
    public static string ToggleFlashlight => Get(nameof(ToggleFlashlight));
    public static string ShakeHint => Get(nameof(ShakeHint));
    public static string NearbyRestaurants => Get(nameof(NearbyRestaurants));
    public static string RefreshLocation => Get(nameof(RefreshLocation));
    public static string Loading => Get(nameof(Loading));
    public static string FavoriteMeals => Get(nameof(FavoriteMeals));
    public static string SearchRecipes => Get(nameof(SearchRecipes));
    public static string PortionLabel => Get(nameof(PortionLabel));
    public static string VoiceNote => Get(nameof(VoiceNote));
    public static string StartListening => Get(nameof(StartListening));
    public static string NutritionChartTitle => Get(nameof(NutritionChartTitle));
    public static string ScanHistory => Get(nameof(ScanHistory));
    public static string MlResultFormat => Get(nameof(MlResultFormat));
    public static string SavedSuccess => Get(nameof(SavedSuccess));
    public static string DeleteSwipeHint => Get(nameof(DeleteSwipeHint));
    public static string OpenHelp => Get(nameof(OpenHelp));
    public static string GoNearby => Get(nameof(GoNearby));
}
